flathub/org.gimp.GIMP

org.gimp.GIMP.WithBase.json
org.gimp.GIMP.app-modules.json
org.gimp.GIMP.json

Not to be merged right now. I am testing for the upcoming GIMP 2.10.2.
The right git tag will have to be added when it will be made.

Bump babl, GEGL, add libheif and test build with GIMP master.

---

org.gimp.GIMP.WithBase.json
org.gimp.GIMP.app-modules.json
org.gimp.GIMP.base-modules.json
org.gimp.GIMP.json

Ghostscript 9.26 is yet another security related related release.
https://www.ghostscript.com/doc/9.26/News.htm

Update ghostscript to 9.26

---

org.gimp.GIMP.base-modules.json

Not tested the builds myself. Let's see how it goes!

Update some dependencies.

---

org.gimp.GIMP.json

Allow support of color profiles for HEIF format.

Bumped libheif dependency.

---

org.gimp.GIMP.json

Test with gimp-2-10 HEAD.

---

org.gimp.GIMP.json
patches/pygtk-Drop-the-PangoFont-find_shaper-virtual-method.patch

-Tweak dependencies
-Use https for downloads
-Patch pygtk
Closes #60, Closes #61

Update SDK to 3.34

---

org.gimp.GIMP.json

Prepare GIMP 2.10.16 release.

---

org.gimp.GIMP.json

This is the first step of #1 
Unlike I said in my last comment I found a way to build the manual as an extension package this PR only set the extension points for the build.

Extension point for manual

---

org.gimp.GIMP.json

Sorry one more PR but I got a clarification on how the locale work and basically setting this attribute should be all that is needed to have the manual languages selectively installed.
Issue #1

Set locale-subset to true for the manual

---

org.gimp.GIMP.json
patches/exiv2-0001-Properly-detect-availability-of-flags-in-cmake-compi.patch
patches/exiv2-0002-fix_solaris_stack_protection_0.27.patch
patches/exiv2-0003-Use-check_cxx_compiler_flags-instead-of-C-version.patch

We only need the interpreter binary for running Lua plug-ins, not the
library.

GIMP beta branch

---

org.gimp.GIMP.json
patches/cairo-mr114-gimp-issue-6210.patch
patches/openexr-no-docs.patch
patches/suitesparse-reduce-build.patch

Once again, just to not be overworked at the last minute. We don't even have an approximate schedule for the 2.10.26 release yet.

Starting preparing 2.10.26

---

README.md

Fallout from 4d654b39dba85ca919ecc399fc59903a88bd702e

Put command into code block

---

org.gimp.GIMP.json
patches/libwmf-autoheader.patch
patches/libwmf-ft2.patch
patches/webkitgtk-41-fix.patch

- added patch to build WebKit
Close #121

Issue #121 - Update runtime to GNOME 41

---

org.gimp.GIMP.json

Issue #129 - remove slang from aalib

---

org.gimp.GIMP.json

Seee https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access

Remove unused vfs dbus talk-name

---

org.gimp.GIMP.json

Let's test some build with latest 2.10 code!

Preparing release of GIMP 2.10.34

---

org.gimp.GIMP.json
patches/0002-Fix-flatpak-release-info-about-JPEG-XL.patch

Patch Changes in version 2.10.34

---

org.gimp.GIMP.json

See issue #196.
Let's try to revert some recent dependency changes to see if one could be the reason for the white text issue.

Try to fix colored text appearing in white.

---

org.gimp.GIMP.json

- added appstream-glib in because it's missing from the platform
Close #251

beta: Update runtime to GNOME 45

---

org.gimp.GIMP.json
patches/gimp-missing-header.patch

This is needed to try to build GMIC 3.3.4

Added patch for missing header (from upstream)

---

org.gimp.GIMP.json
patches/webkitgtk-ruby-fix.patch

Update runtime to GNOME 46

---

org.gimp.GIMP.json
patches/gimp-missing-header-labelstringwidget.patch

This is needed for some plugins to build.
Patch is from usptream. Can be dropped in a future release.

beta: Added missing header (from upstream)

---

org.gimp.GIMP.json

This debloats the final flatpak size a bit by not packaging uneeded files.

Debloat Flatpak

---

org.gimp.GIMP.json

This is not a direct dep of GIMP but of GEGL.
Ported from: NIGHTLY_COMMIT

Move 'suitesparse' to GEGL

---

org.gimp.GIMP.json

gexiv2, exiv2: Update them

---

org.gimp.GIMP.json

suitesparse, openblas: Update them

---

org.gimp.GIMP.json

Update to GNOME platform 46

---

org.gimp.GIMP.json

* imath: Update module 3.1.12
* poppler: Update module to 24.09
* suitesparse: Update module to 7.8.2
* graphviz: Update module to 12.1.1
Also, clean libmypaint locales

Update imath, poppler, suitesparse and graphviz modules

---

org.gimp.GIMP.json

I do not intend, for now, to do the release myself, I am just anticipating part of the job

GIMP 3.0 RC2

---

org.gimp.GIMP.json

~~Depends on: https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/issues/9~~ not anymore due to 0499290fbc991746408b8f3de4522616e4145fde

Enable OpenMP to help suitesparse

---

org.gimp.GIMP.json

Contingency plan for: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1826

Test libbacktrace build (for slightly more detailed dashboard logs)

---

README.md

README: Update "How to do a flatpak release" following our practice

---

org.gimp.GIMP.json

The less the differences the better.

json: Port some unuseful things from Nightly just for easier diffing

---

.gitignore

That file seems to be user env specific.
It isn't mentioned on Flathub docs and the
contributor only had only one contribution.

Remove very obscure .gitignore file

---

org.gimp.GIMP.json

It is needed to the beta branch to not fall behind the master branch.

3.0 Release on Beta

---

org.gimp.GIMP.json

* SuiteSparse: Update v7.9.0.tar.gz to 7.10.1
* Bump gegl to 0.4.58 and GIMP to 3.0.2
Linting done by flathubbot

manifest: Release 3.0.2 on Beta branch

---

.github/workflows/update.yaml
flathub.json

So that we don't have to sync the two branches manually. @brunvonlope, @hfiguiere, thoughts?

Enable dependency updates for both branches

---

.github/workflows/update.yaml
org.gimp.GIMP.json

.github: Enable per branch update check on Beta

---

flathub.json

#437 is pretty clear but it is worth noting on the json for the future.

flathub: Add comment about why we disable flathubbot

---

org.gimp.GIMP.json

manifest: Create GIMP help dir

---

org.gimp.GIMP.json

The recent commit promisses slighty better performance.

manifest: Bump qoi commit
