gegl-0-20-0-fix-with-new-glib-mkenums.patch, org.gimp.BaseApp.json, org.gimp.GIMP.WithBase.json, org.gimp.GIMP.app-modules.json, org.gimp.GIMP.json
This also needs a minor patch to gegl because of a regression
in glib-mkenums (https://bugzilla.gnome.org/show_bug.cgi?id=795008)
=> Update to gnome 3.28 runtime

org.gimp.GIMP.json
According to the documentation we should use "app-id" and not "id" in the manifest:
http://docs.flatpak.org/en/latest/manifests.html
=> Use app-id not id in the manifest

org.gimp.GIMP.json
GIMP doesn't support Wayland... so why have it.
=> Remove unused Wayland permission

org.gimp.GIMP.base-modules.json
We were using versions a bit outdated. Let's update!
Also while doing this, let's enable openjpeg as a dependency of poppler,
since this is now even a GIMP dependency as well, hence we build it
anyway. I have to set -DOpenJPEG_DIR option as it looks like poppler
build system fails to find the installed lib otherwise.
=> Update poppler dependency.

org.gimp.GIMP.json
Also test with HEAD of gimp-2-10 branch to test building current state
of GIMP.
=> Update to babl 0.1.64.

org.gimp.GIMP.json
When building ibus-gtk2, in somme shell commands, it uses
${FLATPAK_DEST}. I don't think it is big of a problem to use old style
absolute directory (probably stays the same), but it's a good practice
and it's nice we have this variable in our manifest to even just know it
exists for other parts of the build.
Also it's better to keep the gtk2 shared module which is (mostly) copied
into our own manifest as close as possible.
=> Sync a bit with shared-modules/gtk2/gtk2.json.

org.gimp.GIMP.json
Yeah already! Some nasty bug was found, so we sneak in a GIMP 2.10.18
even before 2.10.16 is officially announced.
Also take the opportunity to disable update check because flatpak has
auto-update.
Building with HEAD of GEGL as a new release will happen in-between and
we already require the dev version.
=> Prepare GIMP 2.10.18.

.gitignore, org.gimp.GIMP.json
Update ibus-gtk2, which fixes CVE-2019-14822. Also update poppler,
ghostscript, libmypaint, and openBLAS.
Add a .gitignore, fix some incorrect tags, and update several downloads to
use https.
=> Update dependencies and housekeeping

org.gimp.GIMP.json
Closes #59 and answer issue #10, #22 
Currently building: Resynthesizer.
G'Mic is a problem though: we use the GNOME runtime and it needs Qt.
Do we really need the GNOME runtime?
=> Plugins support

org.gimp.GIMP.json, patches/gimp-extension-path.patch
Followup to #75 
This patch make sure that the extension point for plugin and scripts is in the default path for GIMP.
- If either preference hasn't been changed then it will be set to the proper values.
- If one has been changed, it an be reset in the UI and it will have the proper values, but the user will lose the previous one, but that's how the reset work. This case is not very likely though.
- Same with a reset all.
The change to `gimprc.in` isn't necessary at all, but it is for consistency (and in case of upstreaming).
The patch assume GIMP is run in Flatpak. Work needs to be done to have this upstreamable.
=> Make sure the default path for plug-ins and scripts point to the extension point

org.gimp.GIMP.json
GMic complain about GL. So we need enable DRI permissions. I also wonder if GEGL using the GPU wouldn't complain either.
=> Added DRI access

org.gimp.GIMP.json
The Freedesktop SDK's libtiff is not full-featured so there are TIFF
files our build cannot create or open right now. This has been fixed
upstream but won't be available within the year most likely. So let's
build it ourselves for the time being.
Cf. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1117
=> Add libtiff in our build.

org.gimp.GIMP.json
I realize I can only export 8bpc HEIC files. This looks like the
appropriate option to enable 10 and 12-bit file encoding.
=> Build x265 with HIGH_BIT_DEPTH=ON.

org.gimp.GIMP.json
This allows the "Include window decoration" option in Screenshot
plug-in. Thanks to Christopher Davis to raise this option miss in:
https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/364
=> Build libXmu too.

org.gimp.GIMP.json, patches/webkitgtk-fix.patch
- change plugin branch
- add patched for webkitgtk
Closes #84 
Closes #85 
Keeping as draft for now, I ran out of disk space on the install phase if webkitgtk. Will check it build here and test the build.
Also as noted, plugins will need to be updated.
=> Update runtime to Gnome 40

org.gimp.GIMP.json
This will hopefully fix some crashes we are experiencing in Little-CMS
2.10 currently available in the GNOME 40 runtime.
See: https://gitlab.gnome.org/GNOME/gimp/-/issues/6636
=> Build Little-CMS 2.12 ourselves.

org.gimp.GIMP.json
Just because of an annoying build bug (one missing theme file). It's
basically the same as 2.10.26 otherwise.
=> Prepare GIMP 2.10.28.

org.gimp.GIMP.json, patches/openexr-no-docs.patch
Flathub counterpart of https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/492
This required subtle changes to the manifest because the upstream
project no longer publishes separate tarballs with different parts
of the project.
=> Bump openexr from v2.3.0 to v2.5.7

org.gimp.GIMP.json, patches/cairo-mr245-issue325.patch
This is a patch for a very old issue we had in GIMP about character
cut-off because of inappropriate glyph bounds approximation.
The fix is to remove the approximation altogether.
The commit was slightly different because of another change in the same
piece of code in the main dev branch of Cairo, so this patch is a
version doing the same thing on stable Cairo 1.16.0.
See:
https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/245
https://gitlab.gnome.org/GNOME/gimp/-/issues/325
=> patches: new patch for cairo!245.

org.gimp.GIMP.json
- Bump GEGL.
- Bump the GNOME runtime.
- Try to build the HEAD of the `gimp-2-10` branch.
=> Prepare GIMP 2.10.30.

org.gimp.GIMP.json
OpenEXR and mypaint-brushes offer next major versions. GIMP is probably
not ready for the changes in OpenEXR and mypaint-brushes are not yet
finalized. Put their versions under constraints so that automatic PR
creation for dependency bumps can be enabled.
I'd postpone merging this until https://github.com/flathub/flatpak-external-data-checker/pull/265 is merged and a new version of the tool is released.
=> Add version constraints for OpenEXR and mypaint-brushes

org.gimp.GIMP.json
JSON does not support comments and their support in Flatpak is possible
through use of json-glib[0]. This is problematic in fully utilizing
flatpak-external-data-checker because its JSON writer does not respect
existing comments. To solve this, make use of Fltpak's specific
behaviour where a "//" key is explicitely ignored while parsing[1].
[0] https://github.com/flatpak/flatpak-builder/issues/363#issuecomment-710652526
[1] https://github.com/flatpak/flatpak-builder/blob/0e98b7ae191b81ff66d323ad5dabc2762c5f3f0c/src/builder-utils.c#L1250
=> Replace C-style comments with JSON keys ignored by Flatpak

org.gimp.GIMP.json
It requires bumping BABL and GEGL to their latest versions for the build to succeed.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> Update runtime to GNOME 43

org.gimp.GIMP.json
@hfiguiere @HarryMichal @novomesk I need to temporarily revert the GNOME 43 bump, at least from the stable flatpak, because the Glib packed in there contains a major crash bug. It used to be a big crash cause which most/all distributions were even patching a month before an actual GLib (2.74.1) got out with the fix.
Anyway we noticed that the GNOME 43 runtime contains the broken GLib so we started to get crash reports already. Therefore, I'm going to revert the runtime update.
I also asked the runtime maintainers to update GLib in there: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/575
@novomesk If I understood, you absolutely want the runtime 43 for the beta flatpak? I mean, it's a dev build, so we can live with the crash, but if we could avoid to get reports for outdated …
=> Revert GNOME 43 bump because of glib 2 74 0

org.gimp.GIMP.json
GLib has now been updated appropriately to version 2.74.1: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1862
Also reverting down the runtime bump most likely broke plug-ins since they had to be updated when we bumped to GNOME 43. See:
* https://github.com/flathub/org.gimp.GIMP/pull/159#issuecomment-1286129947
* https://gitlab.gnome.org/GNOME/gimp/-/issues/8861
=> Bump back to GNOME runtime version 43.

org.gimp.GIMP.json
The patches don't apply anymore. Also it's a major version update and I haven't checked at all if API is stable and if it still works. Maybe it does, but it needs to be verified manually.
Last but not least, the flathubbot has been spamming us with broken MRs trying to bump this dependency lately. Worse: it breaks other dependency bumps from happening. So let's stick SuiteSparse to < 6.0.0 for the time being to unblock things and stop the bot spamming. We can unblock when one of the package contributors look at this dependency rule in detail (maybe also when org.octave.Octave do the work on their side too since this rule originally came from their manifest; I can see they haven't yet at time of writing).
=> Do not bump SuiteSparse to 6.x versions (at least for now).

org.gimp.GIMP.json
The bot fails to build because since this version, Cairo build is meson-only.
See discussion in: https://gitlab.freedesktop.org/cairo/cairo/-/issues/622
Also using a different source URL, which is the one officially listed in the release news: https://cairographics.org/news/cairo-1.17.8/ I hope it won't clash with Anitya database which seems to favor the Gitlab source. But using static download servers is usually better when possible (especially when recommended by the project itself).
=> Update Cairo to version 1.17.8.

org.gimp.GIMP.json
I may have been too quick to publish the Cairo revert. Babl is a likely culprit. Let's try to revert it and take more time to test.
=> Revert babl for the "white text" bug.

org.gimp.GIMP.json
- poppler: 23.02.0 → 23.04.0
- ghostscript: 10.0.0 → 10.01.0 (also fixes the anitya check, see: https://github.com/flathub/flatpak-external-data-checker/issues/360)
- OpenBLAS: 0.3.21 ⇒ 0.3.23
- libheif: 1.15.1 ⇒ 1.15.2
- GEGL: 0.4.42 ⇒ 0.4.44
=> Sync the stable branch with the dependencies on beta branch.

org.gimp.GIMP.json
Synced back from the beta manifest where these build fine.
=> Bump GNOME runtime, babl and GEGL.

org.gimp.GIMP.json
For some reason, the build to release GIMP 2.10.36 a few days ago failed (I should have followed through): https://buildbot.flathub.org/#/builders/6/builds/79515
I tried to trigger a new build manually, but now I get new errors because Exiv2 just released a new version: https://buildbot.flathub.org/#/builders/42/builds/7201
So anyway updating Exiv2 to finally be able to upload the new GIMP version.
=> Exiv2 version 0.28.1 just got released.

org.gimp.GIMP.json
HEIC is patent-encumbered.  Some distributors or users may prefer not to
have such codecs installed on their system.
libheif has an optional plugin system, where codecs can be compiled as
separate shared objects. At runtime, libheif dynamically loads any such
codecs it finds in its search path. The search path comes out as
/app/lib/libheif, adjacent to the libheif library itself.
Configure libheif to build its libde265 and x265 support as plugins, and
then split the /app/lib/libheif directory into an extension. Move the
libde265 and x265 libraries themselves to a subdirectory, and use
add-ld-path to place /app/lib/libheif/lib onto the library search path
if the extension is installed.
With these changes, the org.gimp.GIMP.HEIC extension will be installed &
uninstalled automatically with …
=> Move HEIC support to an extension

org.gimp.GIMP.json, patches/0002-appdata-remove-group.patch
This should fix the build for `stable`
=> Fix build: remove group GNOME in appstream

org.gimp.GIMP.json
This was already done in beta flatpak: acec036cbee739e852e9358c9dddd246a7085520
See the discussion in: https://gitlab.gnome.org/GNOME/gimp/-/issues/9785
=> Remove custom libjxl build

org.gimp.GIMP.json
Ported from: https://gitlab.gnome.org/GNOME/gimp/-/commit/d071d01666aee5473915f7563f51e9c1f62cc2b6 This is needed because NASA server is making our pipelines fail.
=> cfitsio: Change source repo to a more trustful one

org.gimp.GIMP.json
Let's follow the chronological order of things done by flatpak-builder: clone and patch > configure > build > install > post-install > cleanup
This is specially useful to maintenance, since 'sources' is the most common keyword to be touched and the following depends on 'sources'.
=> Make manifest keywords easier to read

org.gimp.GIMP.json
Also, drop liblab cleanup since it isn't built anymore
=> graphviz: Update to 12.0.0

org.gimp.GIMP.json
This is required to build plugins like GMIC
This is a regression from #321
=> Don't cleanup gexiv2 headers / pkconfig

org.gimp.GIMP.json
This is required by gexiv2 which is required to build plugins like GMIC Follow-up for #348
=> Don't cleanup exiv2 headers / pkconfig

org.gimp.GIMP.json
This should help fixing https://github.com/flathub/org.gimp.GIMP.Plugin.Resynthesizer/issues/14
This is an important change and I will update all the GIMP 3 plugins to work.
=> plug-ins: change the extension path

org.gimp.GIMP.json
First commit: we should not build workshop operations in GEGL.
See: https://gitlab.gnome.org/GNOME/gimp/-/issues/12681#note_2322562
=> Preparing GIMP 3.0.0 RC3 release

org.gimp.GIMP.json
This was added in a93bb3ef0e68f0a4d794189647f3426c1b7de289 and it isn't needed anymore.
=> gegl: Remove obsolete Glib requirement

org.gimp.GIMP.json
Inside "version" make flatpak-external-data-checker fail
=> manifest: Fix OpenBLAS comment position

org.gimp.GIMP.json
See the explanation in: https://gitlab.gnome.org/GNOME/gimp/-/issues/14361
=> manifest: Restrict Gexiv2 module version to the API we support

org.gimp.GIMP.json
Not working yet. Will work after the fix on
org.gimp.GIMP.Manual flatpak build.
=> manifest: Add extension point to 'org.gimp.GIMP.Manual'

org.gimp.GIMP.json
This updates cfitsio to 4.6.2.
=> manifest: Build cfitsio with CMake

org.gimp.GIMP.json
Ported from: https://gitlab.gnome.org/GNOME/gimp/-/commit/47eac319b1d8f4f9eac631037e8183c32a625d47
=> manifest: Avoid noisy warnings about GTK_MODULES
